# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['DatE.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('res/web', 'res/web'),
        ('res/locales', 'res/locales'),
        ('res/assets', 'res/assets'),
    ],
    hiddenimports=[
        'core',
        'core.app',
        'core.server',
        'core.i18n',
        'core.version',
        'core.paths',
        'log',
        'log.activity_log',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'fastapi',
        'uvicorn',
        'pydantic',
        'starlette',
        'email_validator',
        'httptools',
        'websockets',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'tkinter',
        'unittest',
        'test',
        'PySide6.QtNetwork',
        'PySide6.QtOpenGL',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtPdf',
        'PySide6.QtSvg',
        'PySide6.QtVirtualKeyboard',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='DatE',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='res/assets/app_icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[],
    name='DatE',
)
